platform:ios,'8.0'
target 'WYTest'do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'AliyunOSSiOS'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.1'
pod 'IQKeyboardManager'

end
